apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: etcd-deployment
  labels:
    app: etcd-webhook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: etcd-webhook
    spec:
      containers:
        - name: etcd-webhook
          image: registry-internal.cn-hangzhou.aliyuncs.com/sunny_chen/sunny_chen/etcd-webhook:v1
          imagePullPolicy: IfNotPresent
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: etcd-webhook-webhook-certs
